version: "3"
services:
  bunseki:
    image: dannyvankooten/bunseki:latest
    ports:
      - "8080:8080"
    environment:
      - "BUNSEKI_SERVER_ADDR=:8080"
      - "BUNSEKI_GZIP=true"
      - "BUNSEKI_DEBUG=false"
      - "BUNSEKI_DATABASE_DRIVER=mysql"
      - "BUNSEKI_DATABASE_NAME=bunseki"
      - "BUNSEKI_DATABASE_USER=bunseki"
      - "BUNSEKI_DATABASE_PASSWORD=password01"
      - "BUNSEKI_DATABASE_HOST=mysql:3306"
      - "BUNSEKI_SECRET=TWEn6GXQDx45PZfmJWvyGpXf5M8b94bszgw8JcJWEd6WxgrnUkLatS34GwjPTvZb"
    links:
      - "mysql:mysql"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: "mysql:5"
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=false"
      - "MYSQL_DATABASE=bunseki"
      - "MYSQL_PASSWORD=password01"
      - "MYSQL_ROOT_PASSWORD=password01"
      - "MYSQL_USER=bunseki"
    restart: always
